### ISSUE TITLE
Selenium headless not working - workaround to force 4.12.0

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#103]
Have found that when I did a `pipenv update` then ran the code on my local machine, the firefox browser would display briefly. However on the server (with no terminal attached) it couldn't, so errored out, not producing a screenshot

In my Pipfile I've added this for the meantime which works as before
```
#selenium = "*"
# bug where it renders to screen on 4.15.0, and fails on the server
selenium = "==4.12.0"
```

**Comment by GalenReich** [comment]
Great issue Dave, thanks for flagging this. This is probably due to [a change to how Selenium handles headless mode](https://www.selenium.dev/blog/2023/headless-is-going-away/). It should have been raising a deprecation warning before.

**Comment by djhmateer** [comment]
Thank you very much Galen for fixing this!
