### ISSUE TITLE
tiktok_downloader error while installing: subprocess-exited-with-error / metadata-generation-failed

### ISSUE THREAD

**Issue by Tiptop4792** [bellingcat/auto-archiver#109]
Hey y'all! 

I failed installing the archiver, apparently multiple issues with tiktok_downloader. 

I used `pip install ` on Unbuntu 22.04

Did anyone come across it?

Here's my terminal output:

> INFO: pip is looking at multiple versions of tqdm to determine which version is compatible with other requirements. This could take a while.
Collecting tqdm
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
INFO: pip is looking at multiple versions of tiktok-downloader to determine which version is compatible with other requirements. This could take a while.
Collecting tiktok-downloader
  Using cached tiktok_downloader-0.3.4.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.3.3.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.3.2.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Collecting faker
  Using cached Faker-20.1.0-py3-none-any.whl (1.7 MB)
Collecting tiktok-downloader
  Using cached tiktok_downloader-0.3.1.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.3.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting py-mini-racer
  Using cached py_mini_racer-0.6.0-py2.py3-none-manylinux1_x86_64.whl (5.4 MB)
Collecting tiktok-downloader
  Using cached tiktok_downloader-0.2.9.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.2.8.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of tiktok-downloader to determine which version is compatible with other requirements. This could take a while.
  Using cached tiktok_downloader-0.2.7.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.2.6.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.2.5.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.2.4-py3-none-any.whl (10 kB)
  Using cached tiktok_downloader-0.2.3-py3-none-any.whl (15 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached tiktok_downloader-0.2.2-py3-none-any.whl (15 kB)
  Using cached tiktok_downloader-0.2.1-py3-none-any.whl (14 kB)
  Using cached tiktok_downloader-0.1.6-py3-none-any.whl (15 kB)
  Using cached tiktok_downloader-0.1.5.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.1.4.tar.gz (6.6 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.1.3.tar.gz (6.6 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.1.2.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.1.1.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.1.0.tar.gz (6.0 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.0.8.tar.gz (6.0 kB)
  Preparing metadata (setup.py) ... done
  Using cached tiktok_downloader-0.0.7.tar.gz (6.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
 > × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-19_a3jbo/tiktok-downloader_753611509dfa491e9773e1fd59df8d08/setup.py", line 9, in <module>
          long_description=open(path.join(base_dir, "README.md"), encoding="utf-8").read(),
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-19_a3jbo/tiktok-downloader_753611509dfa491e9773e1fd59df8d08/README.md'
      [end of output]
  
>  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

> × Encountered error while generating package metadata.
╰─> See above for output.

> note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Many thanks for looking into this!

**Comment by djhmateer** [comment]
Hi @Tiptop4792 

I use pipenv as shown here on my fork: https://github.com/djhmateer/auto-archiver/blob/v6-test/infra/server-build.sh#L69

Like you I'm using Ubuntu 22.04 and following this build script I've got all dependencies working.

I've not come across your error, but have had many similar (it could be the version of Python for example)

**Comment by msramalho** [comment]
pipenv is used in option 3 here: https://github.com/bellingcat/auto-archiver#option-3---local-installation
