### ISSUE TITLE
Instagram recommended strategies

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#140]
Dear All

Using the latest release of the auto-archiver, and looking for advice on which strategy to use for Instagram currently.

- instagram_api_archiver.py
- instagram_archiver.py
- instagram_tbot_archiver.py

I've got nothing working at the moment 

The instagram_archiver is throwing (username and password are correct it is passing)

`src.auto_archiver.archivers.instagram_archiver:__init__:41 - Unable to finish login (retrying from file): 'dict' object has no attribute 'instagram_self'`

Any guidance much appreciated.

**Comment by djhmateer** [comment]
I'm guessing that this is the current order of preference as in https://github.com/bellingcat/auto-archiver/blob/main/example.orchestration.yaml

**Comment by msramalho** [comment]
Hi @djhmateer 
Order of preference is:
1. instagram_api_archiver.py this is stable but requires [an unofficial API](https://github.com/subzeroid/instagrapi)
2. instagram_archiver.py this has not been tested for some time but some know issues are account blocking
3. instagram_tbot_archiver.py this is fickle but free, do test if it's working as expected

**Comment by djhmateer** [comment]
Thanks @msramalho - I found that the tbot archiver does work, instagram_archiver didn't currently.. so am going with the instagram_api_archiver.
