### ISSUE TITLE
YoutubeDL can return non-video content

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/auto-archiver#15]
Currently this isn't handled well by the archiver. For example, if YoutubeDL returns a PDF, it will attempt to run ffmpeg on it, resulting in an error. We should be ready to handle non-video content coming from YoutubeDL (and more generally, ref #3)

**Comment by msramalho** [comment]
This seems like an important issue, especially since ytd does work on many platforms that no other scraper does.

**Comment by loganwilliams** [comment]
This has been fixed.
