### ISSUE TITLE
archive facebook with archive.ph

### ISSUE THREAD

**Issue by msramalho** [bellingcat/auto-archiver#26]
https://archive.ph/ does not have an API like the Internet Web Archive Wayback machine, although it can archive facebook pages and IWA cannot. Could we use selenium to submit links in the archive.ph UI and thus successfully archive links?

**Comment by loganwilliams** [comment]
Only if we can get past a captcha, which is non-trivial. Also, the operator of archive.today clearly does not want people submitting links in an automated way, which arguably is worth respecting. I wonder if there's a way of making this simpler for researchers though, like a tool that would submit links to the spreadsheet and archive.today at the same time, so it's technically not an automated process but based on manual input. (Would also have someone to solve the captcha).
