### ISSUE TITLE
include exif metadata

### ISSUE THREAD

**Issue by msramalho** [bellingcat/auto-archiver#34]
Add an additional data point containing exif metadata where available, for now can only think of telegram media.

**Comment by raviksharma** [comment]
Hi, I was looking at this issue. It looks like telegram strips off exif metadata from the uploaded images. 

- I tested by downloading t.me link files. 
- I used https://exifdata.com/ (there was differenrce between directly uploading the file from camera and uploading after downloading from telegram)

quick search tells me twitter does the same.

**Comment by msramalho** [comment]
Hi @raviksharma, most social media strip this indeed, one reason why this issue hasn't been prioritized, another is the archiver uploads what it received so metadata can always be accessed at a later stage and we haven't found a great need for it in the tool yet.
That being said, Telegram does not strip the metadata when you upload without compression, re-tested now on the web version, and I'll leave this open in case others find it useful and we can then make it a feature rather than a possibility.

**Comment by msramalho** [comment]
This has been implemented in this enricher: https://github.com/bellingcat/auto-archiver/blob/main/src/auto_archiver/enrichers/metadata_enricher.py

Practice shows it generates a lot of garbage metadata but may still prove useful for some platforms.
