### ISSUE TITLE
Where to host - Azure, EC2, OVH, Hetzner

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#38]
Am currently hosting on my own bare metal server with https://www.proxmox.com/en/ out of my home office

Any recommendations as to where *not* to host . I'm guessing that OVH / Hetzner will be more blocked that anything else.

https://www.ovhcloud.com/en-gb/bare-metal/

I'm testing Azure VM's (West Europe) currently and will report back any differences I find. They are more expensive.

**Comment by djhmateer** [comment]
Azure burstable VM's (B2s) are working very well out of Western Europe database. 4GB of RAM.  Bash deploy script: https://github.com/djhmateer/auto-archiver/blob/main/infra/infra.azcli

**Comment by msramalho** [comment]
Thanks for that, I'll close this as it's more of an open-ended discussion but feel free to drop more comments.
