### ISSUE TITLE
Test and Demo spreadsheet with urls which test all aspects

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#49]
A first step to testable code could be a spreadsheet which has expected output columns. This would make it easy to see if anything isn't working (regression testing).

I've got something already and will improve and post here.

This would also be useful for a demo purposes too, so users can see what is happening (and what should happen)

In order of usefulness to clients / most common links

## Twitter

- 1 image (should work)
- multiple images (should work)
- tweet with media sensitive image(s)
- tweet that brings a login prompt (trick is to get rid of part of the url)
- check tweet image size is max resolution
- tweet that contain a non twitter video URL as intent is probably to get images from tweet

then video:

- 1 video
- multiple videos will not work

## Facebook

- 1 image - will not work
- multiple images - will not work

then video:

- 1 video. Handled by youtubedl
- multiple videos - unusual and wont work

## etc...

In order of developers

- TelethonArchiver (Telegrams API)
- TikTokArchiver (always getting invalid URL so far)
- TwitterAPIArchiver (handles all tweets if API key is there)
- YoutubeDLArchiver (handles youtube, and facebook video)
- TelegramArchiver (backup if telethon doesn't work which is common)
- TwitterArchiver (only if Twitter API not working)
- VkArchiver
- WaybackArchiver

**Comment by djhmateer** [comment]
Demo Sheet Created. Ping me an email davemateer@gmail.com if you'd like access to it and the Google Drive.

![image](https://user-images.githubusercontent.com/111231/178253429-f3ec4b5d-df2a-44b3-b561-074ba5ee040f.png)

**Comment by msramalho** [comment]
closing now due to inactivity.
