### ISSUE TITLE
Support Instagram image posts

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/auto-archiver#54]
It would be helpful to have support for archiving Instagram image posts as well as videos (which are currently archived with youtube-dl). This would likely require additional authentication credentials, like a cookie, to be specified in the configuration file.

**Comment by edsu** [comment]
The new support for [browsertrix-crawler](https://github.com/webrecorder/browsertrix-crawler) snapshots should be able to archive Instagram posts if you configure a browsertrix-profile. As an example see the last two columns in the row containing an Instagram post in [this sheet](https://docs.google.com/spreadsheets/d/1Tk-iJWzT9Sx2-YccuPttL9HcMdZEnhv_OR7Bc6tfeu8/edit#gid=0).
