### ISSUE TITLE
Whisper enhancer should return link when transcription task is too large

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/auto-archiver#77]
Currently the transcription task will timeout and not provide anything to the user.

Instead, it should include a link to read the job results from the job UUID. This would require that this endpoint not require authentication. However, this should be okay.

**Comment by msramalho** [comment]
This has been implemented here: https://github.com/bellingcat/auto-archiver/blob/6e4fb7694013f89c519a068c2aa71e147586206d/src/auto_archiver/enrichers/whisper_enricher.py#L64-L65

The format can still be improved but that would merit an issue in https://github.com/bellingcat/whisperbox-transcribe/
