### ISSUE TITLE
Twitter API changes

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#82]
The free tier of Twitter API does not allow searching of Tweets anymore.

This means that the Twitter API archiver here needs a paid tier to work, however the snscrape archiver works fine.

Just a placeholder issue for clarity. https://davemateer.com/2023/06/29/tweepy-twitter-python-library  gives some more detail and links.

**Comment by msramalho** [comment]
Hi @djhmateer it seems the snscrape scraper is not working either: https://github.com/JustAnotherArchivist/snscrape/issues/996

I've re-enabled the [twitter-archiver hack](https://github.com/bellingcat/auto-archiver/blob/abaf86c77609a68a2495e994ed215728636c3d6e/src/auto_archiver/archivers/twitter_archiver.py#L91) endpoint based on that thread, it's working as of now, don't know for how long :smiling_face_with_tear:

**Comment by djhmateer** [comment]
thanks very much @msramalho - can confirm it is working for now!

**Comment by djhmateer** [comment]
https://github.com/JustAnotherArchivist/snscrape/issues/996  - Twitter has changed so the hack method not working now. I've tested with latest docker version of auto-archiver

```
2023-08-20 10:23:34.685 | DEBUG    | auto_archiver.archivers.twitter_archiver:download_alternative:96 - Trying twitter hack for url='https://twitter.com/RALee85/status/1496790012242837506'
2023-08-20 10:23:34.875 | DEBUG    | auto_archiver.archivers.twitter_archiver:download_alternative:113 - Twitter hack got urls=[]
```

**Comment by msramalho** [comment]
Reopening this issue.

The current status of twitter archiving is: 
1. this repo works if using the WaczArchiverEnricher with a browsertrix-profile. 
2. it should work when using the paid twitter API, but that code needs to be tested with a paid API account, happy to receive feedback/contributions on that.

**Comment by djhmateer** [comment]
Thanks for reopening @msramalho 

I can confirm that with a paid account the twitter_api_archiver is working on the current Docker release.

Am opening another issue for the WaczArchiverEnricher which is failing for me.. [here]()
