### ISSUE TITLE
UX bug: archiving fails if the "url" is replaced with its linked title text

### ISSUE THREAD

**Issue by liliakai** [bellingcat/auto-archiver#83]
When pasting a url in Sheets, a helpful little dialog appears and suggests that you "Replace URL with its title" as linked text (see image below). Auto archiver doesn't know how to handle this format and returns "nothing archived". However, it should be possible to detect and extract the url when the cell value is a link.

<img width="663" alt="Screenshot 2023-08-01 at 16 43 13" src="https://github.com/bellingcat/auto-archiver/assets/1039940/27b92c43-5a1c-42eb-b1bf-8745777bfac9">

**Comment by msramalho** [comment]
closing now due to inactivity.
