### ISSUE TITLE
yt-dlp fix for facebook videos

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#92]
I'm now running yt-dlp from the latest master branch to get a fix for facebook videos.

Thought I'd put a comment here in case it helps. Otherwise we just need to wait until it comes into the next release.

My notes on how I did it:

https://davemateer.com/2023/09/06/yt-dlp-running-master

**Comment by msramalho** [comment]
Thanks for sharing, we'll update it once it gets released into pypi.
