### ISSUE TITLE
pdqhash problem on Pipfile update

### ISSUE THREAD

**Issue by djhmateer** [bellingcat/auto-archiver#99]
When installing on Ubuntu 20.04 I found that

```bash
# this would error out 
pipenv update
```
But by commenting out  `pdqhash = "*"` from the Pipfile I could get it to work.

On my Ubuntu 22.04 WSL2 it all installed fine.

https://github.com/faustomorales/pdqhash-python

May be a problem on pdqhash side,.

**Comment by msramalho** [comment]
Hi @djhmateer what was the error, could you get it working on a previous version of pdqhash? 
That library is quirky to install since it requires `apt install g++` so it can be built on ubuntu.

**Comment by djhmateer** [comment]
Thanks Miguel - have moved production servers to 22.04 now, and once embedded in I'm hoping to turn on the duplicate detection. Hopefully I can get pdqhash working.

**Comment by djhmateer** [comment]
I can confirm that on Ubuntu 22.04 (both WSL2 and native) pdqhash works using the Pipfile and pipenv update.
